### ISSUE TITLE
Ubuntu 24.04: I cannot close the app properly. Is it a bug?

### ISSUE THREAD

**Issue by sameersharma2006** [sameersharma2006/xdman-snap#3]
On Ubuntu 24.04. I cannot close the app properly. Is it a bug?

_Originally posted by @dnet890 in https://github.com/sameersharma2006/xdman-snap/issues/2#issuecomment-2321228560_

**Comment by sameersharma2006** [comment]
@dnet890 Tracking your query/bug in this issue as that issue was for different purpose.

I will need a bit elaboration on what exactly happened ?

> In General, the app uses system-tray and hence will continue running in the background when you close it via the  
   window border close function/icon.
   To initiate a full exit, select the hamburger menu and at the bottom select the `exit` option.

**Comment by dnet890** [comment]
I see. because on old Java app. we can kill the process by right click of the icon taskbar and you can see the exit button or use xkill to kill the app directly. that means this is quite big change right?

**Comment by sameersharma2006** [comment]
> I see. because on old Java app. we can kill the process by right click of the icon taskbar and you can see the exit button or use xkill to kill the app directly. that means this is quite big change right?

AFAIK the tray icon in not fully implemented as its a BETA release(https://github.com/subhra74/xdm/discussions/768).
If the upstream publishes a new release with the fix i will publish it as a snap accordingly.

P.S. The BETA version is not written in Java but in Dotnet & Gtk etc.

**Comment by sameersharma2006** [comment]
Closing this since its related to upstream and there is nothing that i can resolve at the current moment.
